
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi
spec:
  releaseName: csi
  targetNamespace: kube-system
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store-provider-azure
        namespace: flux-system
      version: "1.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3