
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aad-pod
spec:
  releaseName: aad-pod
  targetNamespace: kube-system
  chart:
    spec:
      chart: aad-pod-identity
      sourceRef:
        kind: HelmRepository
        name: aad-pod-identity
        namespace: flux-system
      version: "4.1.6"
  interval: 1h0m0s
  install:
    remediation:
      retries: 1